jobs:
  include:
    - language: python
      python: 3.7
      install:
        - pip install coverage
      before_script:
        - cd SomePythonProject
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - coverage run -m unittest discover test
      after_script:
        - ./cc-test-reporter after-build --debug --exit-code $TRAVIS_TEST_RESULT
    
    - language: cpp
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test

      before_install:
        - pip install --user cpp-coveralls
      before_script: cd SomeC++Project
      script:
        - mkdir build
        - cd build
        - cmake ..
        - cmake --build .
        - ctest