on: ["push"]

name: Example Test Routine on Two Project

jobs:
  test-python-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Python 3.x
      uses: actions/setup-python@master
      with:
        python-version: '3.x'

    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage

    - name: Scripts commands- testing python project
      run: |
        cd PythonProjectExample
        coverage run -m unittest discover test
        coverage xml

    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./PythonProjectExample/coverage.xml

  test-cpp-project:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Dependencies
      run: |
        sudo apt-get install -y lcov
        pip install --user cpp-coveralls
        pip install gcovr
    - name: Scripts commands- build and run tests
      run: |
        cd C++ProjectExample
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug ..  -Dtest=ON
        make
        make coverage_testFoo
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./C++ProjectExample/build/coverage_testFoo.info.cleaned

    