on: ["push", "pull_request"]

name: Test Coveralls Parallel

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_number:
          - 1
          - 2
    steps:
    - uses: actions/checkout@master
    - name: Use Python 3.x
      uses: actions/setup-python@master
      with:
        version: 3.x

    - name: coverage and coveralls install
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install coveralls

    - name: Test ${{ matrix.test_number }}
      run: |
        cd SomePythonProjectCoveralls
        coverage run -m unittest discover test
        coverage report
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: run-${{ matrix.test_number }}
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true